trino-0.313.0.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
trino-0.313.0.dist-info/LICENSE,sha256=z8d0m5b2O9McPEK1xHG_dWgUBT6EfBDz6wA0F7xSPTA,11358
trino-0.313.0.dist-info/METADATA,sha256=QnyYABtHOiWwxkVxN_CvDgiT5s4sXKJd7_KXU3QTaOY,2002
trino-0.313.0.dist-info/RECORD,,
trino-0.313.0.dist-info/WHEEL,sha256=ewwEueio1C2XeHTvT17n8dZUJgOvyCWCt0WVNLClP9o,92
trino-0.313.0.dist-info/entry_points.txt,sha256=AqOXjA81sfu9pfFCI0i0RVgOXQqSdsOyLFgj4nXtzBc,69
trino-0.313.0.dist-info/top_level.txt,sha256=iHqQtrm6g-HE386hcIwGWLOIdCCxvE7jM7xR7z5muHc,6
trino/__init__.py,sha256=x7rJEPRgn6qOTYEV5j5nOLlFFNzmrXaxrEgCQ6REHOw,778
trino/__pycache__/__init__.cpython-39.pyc,,
trino/__pycache__/auth.cpython-39.pyc,,
trino/__pycache__/client.cpython-39.pyc,,
trino/__pycache__/constants.cpython-39.pyc,,
trino/__pycache__/dbapi.cpython-39.pyc,,
trino/__pycache__/exceptions.cpython-39.pyc,,
trino/__pycache__/logging.cpython-39.pyc,,
trino/__pycache__/transaction.cpython-39.pyc,,
trino/auth.py,sha256=ocz6XyoMBDOt-VFLoe0uYknp7aNFxVx1IWivdVDWpbg,15358
trino/client.py,sha256=kLr89Mt1yckZDOlcvMCNVu76CVKEEl5lcR_O-1FJtcg,26384
trino/constants.py,sha256=UZylN0AZLPNNPCSQlyPGz-GM4_464yehea2o1R_3AX4,1573
trino/dbapi.py,sha256=gokxB8vI3Wta6QRXKh9Br14jfKO6EYbzf0G1u43fK9c,20353
trino/exceptions.py,sha256=C5M9XtvNR-ayT69oOmm6vtoNaQPh8jF5XsCfOxeMFlY,5281
trino/logging.py,sha256=SURBHgjtl662ViSSipad25QLmBr0IQO22bN3b7d3ePo,765
trino/sqlalchemy/__init__.py,sha256=Jz018lYnwlVFZN09KgOFTEHV3vr9oG8_KLOwTsPdFFY,657
trino/sqlalchemy/__pycache__/__init__.cpython-39.pyc,,
trino/sqlalchemy/__pycache__/compiler.cpython-39.pyc,,
trino/sqlalchemy/__pycache__/datatype.cpython-39.pyc,,
trino/sqlalchemy/__pycache__/dialect.cpython-39.pyc,,
trino/sqlalchemy/__pycache__/error.cpython-39.pyc,,
trino/sqlalchemy/compiler.py,sha256=6LlrNUlSfpFv4M_smA74Wr-UermF_SangSeLaxaBOs4,3612
trino/sqlalchemy/datatype.py,sha256=6UP9-t2lhAqjObXEnBzqra5cnZX4AKPOlHN7LQCO53M,6739
trino/sqlalchemy/dialect.py,sha256=85Bu83AbyPP-hckFbsJzIcgesLsFNH6dFCYkKPO685U,13217
trino/sqlalchemy/error.py,sha256=LauZELjHB5sF6H6yQZW5Hteqyh70CSayNDfyRYh4nJo,1099
trino/transaction.py,sha256=8UYQLVoZWY6ybugRmvAMtvk2UevA61musU99haq7Z8w,3429
